<?php

/**
 * @file
 * This is a simple module implementing a webform hook to offer Gallatin-specific lists
 * to be used as options in form components.
 */

/**
 * Implementation of hook_webform_select_options_info().
 */
function webform_gallatin_lists_webform_select_options_info() {
  $items = array();

  $items['united_states_canada'] = array(
    'title' => t('US states/Canadian Provinces'),
    'options callback' => '_united_states_canada',
    'file' => 'includes/webform.options.inc',
  );
  $items['class_advisers'] = array(
    'title' => t('Class Advisers'),
    'options callback' => '_class_advisers',
    'file' => 'includes/webform.options.inc',
  );
  $items['academic_advisers'] = array(
    'title' => t('Academic Advisers'),
    'options callback' => '_academic_advisers',
    'file' => 'includes/webform.options.inc',
  );
  $items['ap_courses'] = array(
    'title' => t('AP Courses'),
    'options callback' => '_ap_courses',
    'file' => 'includes/webform.options.inc',
  );
  return $items;
}


/**
 * Options list containing United States states and territories.
 */
function _united_states_canada($component, $flat, $arguments) {
  return array(
    'Canadian Provinces' => array(
    'AB' => t('Alberta'),
    'BC' => t('British Columbia'),
    'MB' => t('Manitoba'),
    'NB' => t('New Brunswick'),
    'NF' => t('New Foundland'),
    'NT' => t('Northwest Territories'),
    'NS' => t('Nova Scotia'),
    'NU' => t('Nunavut'),
    'ON' => t('Ontario'),
    'PE' => t('Prince Edward Island'),
    'QC' => t('Quebec'),
    'SK' => t('Saskatchewan'),
    'YT' => t('Yukon Territory')
    ),
// — Second option group
'US States' => array(
    'AL' => t('Alabama'),
    'AK' => t('Alaska'),
    'AS' => t('American Samoa'),
    'AZ' => t('Arizona'),
    'AR' => t('Arkansas'),
    'CA' => t('California'),
    'CO' => t('Colorado'),
    'CT' => t('Connecticut'),
    'DE' => t('Delaware'),
    'DC' => t('District of Columbia'),
    'FL' => t('Florida'),
    'GA' => t('Georgia'),
    'GU' => t('Guam'),
    'HI' => t('Hawaii'),
    'ID' => t('Idaho'),
    'IL' => t('Illinois'),
    'IN' => t('Indiana'),
    'IA' => t('Iowa'),
    'KS' => t('Kansas'),
    'KY' => t('Kentucky'),
    'LA' => t('Louisiana'),
    'ME' => t('Maine'),
    'MH' => t('Marshall Islands'),
    'MD' => t('Maryland'),
    'MA' => t('Massachusetts'),
    'MI' => t('Michigan'),
    'MN' => t('Minnesota'),
    'MS' => t('Mississippi'),
    'MO' => t('Missouri'),
    'MT' => t('Montana'),
    'NE' => t('Nebraska'),
    'NV' => t('Nevada'),
    'NH' => t('New Hampshire'),
    'NJ' => t('New Jersey'),
    'NM' => t('New Mexico'),
    'NY' => t('New York'),
    'NC' => t('North Carolina'),
    'ND' => t('North Dakota'),
    'MP' => t('Northern Marianas Islands'),
    'OH' => t('Ohio'),
    'OK' => t('Oklahoma'),
    'OR' => t('Oregon'),
    'PW' => t('Palau'),
    'PA' => t('Pennsylvania'),
    'PR' => t('Puerto Rico'),
    'RI' => t('Rhode Island'),
    'SC' => t('South Carolina'),
    'SD' => t('South Dakota'),
    'TN' => t('Tennessee'),
    'TX' => t('Texas'),
    'UT' => t('Utah'),
    'VT' => t('Vermont'),
    'VI' => t('Virgin Islands'),
    'VA' => t('Virginia'),
    'WA' => t('Washington'),
    'WV' => t('West Virginia'),
    'WI' => t('Wisconsin'),
    'WY' => t('Wyoming')
    )
  );
}

/**
 * Options list containing Class Advisers and emails.
 */
function _class_advisers($component, $flat, $arguments) {
  return array(
    'yt21@nyu.edu' => t('Yevgeniya Traps (First-year)'),
    'cyd.cipolla@nyu.edu' => t('Cyd Cipolla (Sophomore)'),
    'mag19@nyu.edu' => t('Matthew Gregory (Junior)'),
    'meredith.theeman@nyu.edu' => t('Meredith Theeman (Senior)'),
    'benjamin.brooks@nyu.edu' => t('Benjamin Brooks (Senior)'),
    'jss518@nyu.edu' => t('Joshua Shirkey (Transfer)'),
    'lad421@nyu.edu' => t('Lisa Daily (Transfer)')
  );
}

/**
 * Options list containing Academic advisers.
 */
function _academic_advisers($component, $flat, $arguments) {
	return array(
	'na19@nyu.edu' => t('Nancy Agabian'),
	'ca5@nyu.edu' => t('Cynthia Allen'),
	'ra281@nyu.edu' => t('Rebecca Amato'),
	'pya1@nyu.edu' => t('Piper Anderson'),
	'pja7@nyu.edu' => t('Peder Anker'),
	'sa234@nyu.edu' => t('Sinan Antoon'),
	'jaa12@nyu.edu' => t('Julie Avina'),
	'gb97@nyu.edu' => t('Gianpaolo Baiocchi'),
	'jb52@nyu.edu' => t('Jennifer Berg'),
	'vab3@nyu.edu' => t('Victoria Blythe'),
	'cb145@nyu.edu' => t('Christopher Bram'),
	'bfb4@nyu.edu' => t('Benjamin Brooks'),
	'wc24@nyu.edu' => t('William Caspary'),
	'jc46@nyu.edu' => t('John Castellano'),
	'puc1@nyu.edu' => t('Paula Chakravartty'),
	'charua01@nyu.edu' => t('Anthony Charuvastra'),
	'nc518@nyu.edu' => t('Ngina  Chiteji'),
	'ac31@nyu.edu' => t('Ann Chwatsky'),
	'cc176@nyu.edu' => t('Cyd Cipolla'),
	'ec15@nyu.edu' => t('Eugene Cittadino'),
	'nc25@nyu.edu' => t('Nina Cornyetz'),
	'mcs11@nyu.edu' => t('Marie Cruz Soto'),
	'tjc202@nyu.edu' => t('Terence Culver'),
	'kad9@nyu.edu' => t('Kimberly DaCosta'),
	'lad421@nyu.edu' => t('Lisa Daily'),
	'ld41@nyu.edu' => t('Lauren Davis'),
	'ad159@nyu.edu' => t('Anne Dewitt'),
	'kkd2000@nyu.edu' => t('Kristoffer Diaz'),
	'mdd3@nyu.edu' => t('Michael Dinwiddie'),
	'sd47@nyu.edu' => t('Stephen Duncombe'),
	'gte1@nyu.edu' => t('Gregory Erickson'),
	'sjf1@nyu.edu' => t('Salvatore Fallica'),
	'jaf3@nyu.edu' => t('June Foley'),
	'vf20@nyu.edu' => t('Valerie Forman'),
	'sf1563@nyu.edu' => t('Sara Franklin'),
	'hmf2@nyu.edu' => t('Hallie Franks'),
	'rcf2@nyu.edu' => t('Rosalind Fredericks'),
	'lef3@nyu.edu' => t('Lise Friedman'),
	'sf2@nyu.edu' => t('Sharon Friedman'),
	'alg16@nyu.edu' => t('Andrea Gadberry'),
	'dbg3@nyu.edu' => t('D.B. Gilles'),
	'lg3@nyu.edu' => t('Lisa Goldfarb'),
	'djg3@nyu.edu' => t('Donna Goodman'),
	'jag17@nyu.edu' => t('Judith Greenberg'),
	'mag19@nyu.edu' => t('Matthew  Gregory'),
	'hrg2@nyu.edu' => t('Hannah Gurman'),
	'rh388@nyu.edu' => t('Rahul Hamid'),
	'eh82@nyu.edu' => t('Ethan Harkness'),
	'ljh250@nyu.edu' => t('Louise Harpman'),
	'rmh1@nyu.edu' => t('Richard Hendler'),
	'ach382@nyu.edu' => t('Alison Heslin'),
	'sh25@nyu.edu' => t('Scott Hightower'),
	'dah17@nyu.edu' => t('Darrel Holnes'),
	'jh129@nyu.edu' => t('Justin Holt'),
	'kah3@nyu.edu' => t('Karen Hornick'),
	'kdh4@nyu.edu' => t('Kristin Horton'),
	'abh5@nyu.edu' => t('A.B. Huber'),
	'ssh1@nyu.edu' => t('Steven Hutkins'),
	'mwj214@nyu.edu' => t('Myles Jackson'),
	'mwj3@nyu.edu' => t('Mitchell  Joachim'),
	'tlj3@nyu.edu' => t('Trevor Jockims'),
	'nk50@nyu.edu' => t('Nina Katchadourian'),
	'rtk1@nyu.edu' => t('Rosanne Kennedy'),
	'bmk7@nyu.edu' => t('Bruce King'),
	'dmk6@nyu.edu' => t('David King'),
	'eck257@nyu.edu' => t('Eugenia Kisin'),
	'smk21@nyu.edu' => t('Scott Korb'),
	'al71@nyu.edu' => t('Antonio Lauria-Perricelli'),
	'bl466@nyu.edu' => t('Bradley Lewis'),
	'al260@nyu.edu' => t('Andrew Libby'),
	'ml122@nyu.edu' => t('Moya Luckett'),
	'ral13@nyu.edu' => t('Ritty Lukose'),
	'jmm2@nyu.edu' => t('Julie Malnig'),
	'pgm3@nyu.edu' => t('Patrick McCreery'),
	'elm1@nyu.edu' => t('Edward Melnick'),
	'em113@nyu.edu' => t('Eve Meltzer'),
	'km96@nyu.edu' => t('Keith Miller'),
	'mm11@nyu.edu' => t('Mary Mirabella'),
	'am128@nyu.edu' => t('Ali Mirsepassi'),
	'mm6439@nyu.edu' => t('Meleko Mokgosi'),
	'sem2@nyu.edu' => t('Sara Murphy'),
	'cn23@nyu.edu' => t('Chitra Neogy'),
	'vn10@nyu.edu' => t('Vasuki Nesiah'),
	'ccp1@nyu.edu' => t('Crystal Parsons'),
	'akp220@nyu.edu' => t('Amanda Petrusich'),
	'kpf2@nyu.edu' => t('Kimberly Phillips-Fein'),
	'sep1@nyu.edu' => t('Stacy Pies'),
	'mp993@nyu.edu' => t('Millery Polyne'),
	'tp32@nyu.edu' => t('Todd Burke Porterfield'),
	'kop2001@nyu.edu' => t('Kathryn Posin'),
	'jrp6@nyu.edu' => t('Robin Powell'),
	'mtp5@nyu.edu' => t('Myisha Priest'),
	'pr9@nyu.edu' => t('Peter Rajsingh'),
	'bpr212@nyu.edu' => t('Benjamin Ratliff'),
	'wsr1@nyu.edu' => t('William Rayner'),
	'mr105@nyu.edu' => t('Mark Read'),
	'jar31@nyu.edu' => t('Jacob Remes'),
	'ajr6@nyu.edu' => t('Andrew Romig'),
	'ir39@nyu.edu' => t('Nancy Rubino'),
	'ar31@nyu.edu' => t('Antonio Rutigliano'),
	'ls71@nyu.edu' => t('Laszlo Santha'),
	'sls11@nyu.edu' => t('Stephanie Santiago'),
	'ls33@nyu.edu' => t('Leslie Satin'),
	'es38@nyu.edu' => t('Eugene Secunda'),
	'des1@nyu.edu' => t('Dennis Shasha'),
	'jss518@nyu.edu' => t('Joshua Shirkey'),
	'gms1@nyu.edu' => t('George Shulman'),
	'ls104@nyu.edu' => t('Laura Slatkin'),
	'as3683@nyu.edu' => t('Aviva Slesin'),
	'jls9@nyu.edu' => t('Judith Sloan'),
	'als10@nyu.edu' => t('Amy Spellacy'),
	'ms5100@nyu.edu' => t('Matthew Stanley'),
	'kms5@nyu.edu' => t('Kristi Steinmetz'),
	'jkt1@nyu.edu' => t('John Tchen'),
	'mlt8@nyu.edu' => t('Meredith  Theeman'),
	'st35@nyu.edu' => t('Selma Thompson'),
	'yt21@nyu.edu' => t('Yevgeniya Traps'),
	'ct36@nyu.edu' => t('Christopher Trogan'),
	'vv2@nyu.edu' => t('Vasu Varadhan'),
	'gtv2@nyu.edu' => t('Gregory Vargo'),
	'av48@nyu.edu' => t('Alejandro Velasco'),
	'ev247@nyu.edu' => t('Eugene Vydrin'),
	'lmw242@nyu.edu' => t('Lauren Walsh'),
	'slw13@nyu.edu' => t('Susanne Wofford')
	);
}

/**
 * Options list containing AP Courses.
 */
function _ap_courses($component, $flat, $arguments) {
  return array(
            'Art History' => t('Art History'),
            'Biology' => t('Biology'),
            'Calculus AB' => t('Calculus AB'),
            'Calculus BC' => t('Calculus BC'),
            'Chemistry' => t('Chemistry'),
            'Chinese Language and Culture' => t('Chinese Language and Culture'),
            'Computer Science A' => t('Computer Science A'),
            'Computer Science AB' => t('Computer Science AB'),
            'English Literature' => t('English Literature'),
            'Environmental Science' => t('Environmental Science'),
            'European History' => t('European History'),
            'French Language' => t('French Language'),
            'French Literature' => t('French Literature'),
            'German Language' => t('German Language'),
            'Italian Language and Culture' => t('Italian Language and Culture'),
            'Japanese Language and Culture' => t('Japanese Language and Culture'),
            'Latin Literature' => t('Latin Literature'),
            'Latin: Vergil' => t('Latin: Vergil'),
            'Macroeconomics' => t('Macroeconomics'),
            'Microeconomics' => t('Microeconomics'),
            'Physics B' => t('Physics B'),
            'Physics C—Mech' => t('Physics C—Mech'),
            'Physics C—E&amp;M' => t('Physics C—E&amp;M'),
            'Politics (U.S. Government and Politics)' => t('Politics (U.S. Government and Politics)'),
            'Politics (Comp. Government and Politics)' => t('Politics (Comp. Government and Politics)'),
            'Psychology' => t('Psychology'),
            'Spanish Language' => t('Spanish Language'),
            'Spanish Literature' => t('Spanish Literature'),
            'Statistics' => t('Statistics'),
            'U.S. History' => t('U.S. History'),
            'World History' => t('World History')
  );
}