<?php

/**
 * @file
 * This is a simple module implementing a webform hook to offer Gallatin-specific lists
 * to be used as options in form components.
 */

/**
 * Implementation of hook_webform_select_options_info().
 */
function webform_gallatin_lists_webform_select_options_info() {
  $items = array();

  $items['united_states_canada'] = array(
    'title' => t('US states/Canadian Provinces'),
    'options callback' => '_united_states_canada',
    'file' => 'includes/webform.options.inc',
  );
  $items['class_advisers'] = array(
    'title' => t('Class Advisers'),
    'options callback' => '_class_advisers',
    'file' => 'includes/webform.options.inc',
  );
  $items['academic_advisers'] = array(
    'title' => t('Academic Advisers'),
    'options callback' => '_academic_advisers',
    'file' => 'includes/webform.options.inc',
  );
  $items['ap_courses'] = array(
    'title' => t('AP Courses'),
    'options callback' => '_ap_courses',
    'file' => 'includes/webform.options.inc',
  );
  
  $items['affinity_groups'] = array(
    'title' => t('Affinity Groups'),
    'options callback' => '_affinity_groups',
    'file' => 'includes/webform.options.inc',
  );
    $items['lahc'] = array(
    'title' => t('LAHC Requirements'),
    'options callback' => '_lahc',
    'file' => 'includes/webform.options.inc',
  );
  $items['alum'] = array(
    'title' => t('Alumni Years'),
    'options callback' => '_alum',
    'file' => 'includes/webform.options.inc',
  );
  return $items;
}


/**
 * Options list containing United States states and territories.
 */
function _united_states_canada($component, $flat, $arguments) {
  return array(
    'Canadian Provinces' => array(
    'AB' => t('Alberta'),
    'BC' => t('British Columbia'),
    'MB' => t('Manitoba'),
    'NB' => t('New Brunswick'),
    'NF' => t('New Foundland'),
    'NT' => t('Northwest Territories'),
    'NS' => t('Nova Scotia'),
    'NU' => t('Nunavut'),
    'ON' => t('Ontario'),
    'PE' => t('Prince Edward Island'),
    'QC' => t('Quebec'),
    'SK' => t('Saskatchewan'),
    'YT' => t('Yukon Territory')
    ),
// — Second option group
'US States' => array(
    'AL' => t('Alabama'),
    'AK' => t('Alaska'),
    'AS' => t('American Samoa'),
    'AZ' => t('Arizona'),
    'AR' => t('Arkansas'),
    'CA' => t('California'),
    'CO' => t('Colorado'),
    'CT' => t('Connecticut'),
    'DE' => t('Delaware'),
    'DC' => t('District of Columbia'),
    'FL' => t('Florida'),
    'GA' => t('Georgia'),
    'GU' => t('Guam'),
    'HI' => t('Hawaii'),
    'ID' => t('Idaho'),
    'IL' => t('Illinois'),
    'IN' => t('Indiana'),
    'IA' => t('Iowa'),
    'KS' => t('Kansas'),
    'KY' => t('Kentucky'),
    'LA' => t('Louisiana'),
    'ME' => t('Maine'),
    'MH' => t('Marshall Islands'),
    'MD' => t('Maryland'),
    'MA' => t('Massachusetts'),
    'MI' => t('Michigan'),
    'MN' => t('Minnesota'),
    'MS' => t('Mississippi'),
    'MO' => t('Missouri'),
    'MT' => t('Montana'),
    'NE' => t('Nebraska'),
    'NV' => t('Nevada'),
    'NH' => t('New Hampshire'),
    'NJ' => t('New Jersey'),
    'NM' => t('New Mexico'),
    'NY' => t('New York'),
    'NC' => t('North Carolina'),
    'ND' => t('North Dakota'),
    'MP' => t('Northern Marianas Islands'),
    'OH' => t('Ohio'),
    'OK' => t('Oklahoma'),
    'OR' => t('Oregon'),
    'PW' => t('Palau'),
    'PA' => t('Pennsylvania'),
    'PR' => t('Puerto Rico'),
    'RI' => t('Rhode Island'),
    'SC' => t('South Carolina'),
    'SD' => t('South Dakota'),
    'TN' => t('Tennessee'),
    'TX' => t('Texas'),
    'UT' => t('Utah'),
    'VT' => t('Vermont'),
    'VI' => t('Virgin Islands'),
    'VA' => t('Virginia'),
    'WA' => t('Washington'),
    'WV' => t('West Virginia'),
    'WI' => t('Wisconsin'),
    'WY' => t('Wyoming')
    )
  );
}

/**
 * Options list containing Class Advisers and emails.
 */
function _class_advisers($component, $flat, $arguments) {
  return array(
    'yt21@nyu.edu' => t('Yevgeniya Traps (First-year)'),
    'cyd.cipolla@nyu.edu' => t('Cyd Cipolla (Sophomore)'),
    'imm270@nyu.edu' => t('Irene Morrison-Moncure (Junior)'),
    'meredith.theeman@nyu.edu' => t('Meredith Theeman (Senior)'),
    'mag19@nyu.edu' => t('Matthew Gregory (Senior)'),
    'jss518@nyu.edu' => t('Joshua Shirkey (Transfer)'),
    'lad421@nyu.edu' => t('Lisa Daily (Transfer)')
  );
}

/**
 * Options list containing Academic advisers.
 */
function _academic_advisers($component, $flat, $arguments) {
	return array(
'taa2@nyu.edu' => t('Thomas Abercrombie'),
'na19@nyu.edu' => t('Nancy Agabian'),
'ia31@nyu.edu' => t('Ido Aharoni'),
'aa89@nyu.edu' => t('Alisha Ali'),
'ca5@nyu.edu' => t('Cynthia Allen'),
'ra281@nyu.edu' => t('Rebecca Amato'),
'pya1@nyu.edu' => t('Piper Anderson'),
'pja7@nyu.edu' => t('Peder Anker'),
'sa234@nyu.edu' => t('Sinan Antoon'),
'jaa12@nyu.edu' => t('Julie Avina'),
'gb97@nyu.edu' => t('Gianpaolo Baiocchi'),
'apb279@nyu.edu' => t('Alixandra Barasch'),
'gac277@nyu.edu' => t('Gabriel Barcia-Colombo'),
'ab3286@nyu.edu' => t('Amber Benezra'),
'jb52@nyu.edu' => t('Jennifer Berg'),
'gdb234@nyu.edu' => t('Geoff Berman'),
'jb2621@nyu.edu' => t('Jamie Berthe'),
'jlb233@nyu.edu' => t('Jamie Bianco'),
'djb1@nyu.edu' => t('Deborah Borisoff'),
'mmb7@nyu.edu' => t('Mary Brabeck'),
'cb145@nyu.edu' => t('Christopher Bram'),
'jdb453@nyu.edu' => t('Jenna Brayton'),
'amb683@nyu.edu' => t('Alexis Britez'),
'ab1125@nyu.edu' => t('Alrick Brown'),
'klb5@nyu.edu' => t('Kathryn Buck'),
'jc48@nyu.edu' => t('Jeffrey Carr'),
'wc24@nyu.edu' => t('William Caspary'),
'jc46@nyu.edu' => t('John Castellano'),
'puc1@nyu.edu' => t('Paula Chakravartty'),
'charua01@nyu.edu' => t('Anthony Charuvastra'),
'nc518@nyu.edu' => t('Ngina Chiteji'),
'ac31@nyu.edu' => t('Ann Chwatsky'),
'cc176@nyu.edu' => t('Cyd Cipolla'),
'ec15@nyu.edu' => t('Eugene Cittadino'),
'ktc4@nyu.edu' => t('Kwami Coleman'),
'sjc243@nyu.edu' => t('Sybil Cooksey'),
'aec391@nyu.edu' => t('Amy Cordileone'),
'jc266@nyu.edu' => t('Julian Cornell'),
'nc25@nyu.edu' => t('Nina Cornyetz'),
'jec1@nyu.edu' => t('Juan Corradi'),
'mcs11@nyu.edu' => t('Marie Cruz Soto'),
'tjc202@nyu.edu' => t('Terence Culver'),
'kad9@nyu.edu' => t('Kimberly DaCosta'),
'lad421@nyu.edu' => t('Lisa Daily'),
'md155@nyu.edu' => t('Mehmet Darakcioglu'),
'ld41@nyu.edu' => t('Lauren Davis'),
'kd1025@nyu.edu' => t('Kristen Day'),
'ad159@nyu.edu' => t('Anne Dewitt'),
'kkd2000@nyu.edu' => t('Kristoffer Diaz'),
'mdd3@nyu.edu' => t('Michael Dinwiddie'),
'id10@nyu.edu' => t('Imani Douglas'),
'sd47@nyu.edu' => t('Stephen Duncombe'),
'de552@nyu.edu' => t('David Elcott'),
'de32@nyu.edu' => t('Deena Engel'),
'gte1@nyu.edu' => t('Gregory Erickson'),
'alf371@nyu.edu' => t('Anne-Laure Fayard'),
'jf2035@nyu.edu' => t('Joseph Ferrara'),
'jaf3@nyu.edu' => t('June Foley'),
'vf20@nyu.edu' => t('Valerie Forman'),
'sf1563@nyu.edu' => t('Sara Franklin'),
'hmf2@nyu.edu' => t('Hallie Franks'),
'rcf2@nyu.edu' => t('Rosalind Fredericks'),
'df101@nyu.edu' => t('Daniel Freeman'),
'lef3@nyu.edu' => t('Lise Friedman'),
'sf2@nyu.edu' => t('Sharon Friedman'),
'af1752@nyu.edu' => t('Armando Fuentes'),
'alg16@nyu.edu' => t('Andrea Gadberry'),
'bg87@nyu.edu' => t('Billie Gastic'),
'dbg3@nyu.edu' => t('Donald Gilles'),
'fg4@nyu.edu' => t('Faye Ginsburg'),
'lg3@nyu.edu' => t('Lisa Goldfarb'),
'djg3@nyu.edu' => t('Donna Goodman'),
'jag17@nyu.edu' => t('Judith Greenberg'),
'lbg251@nyu.edu' => t('Lauren Greenspan'),
'mag19@nyu.edu' => t('Matthew Gregory'),
'pcg207@nyu.edu' => t('Paul Grimstad'),
'hrg2@nyu.edu' => t('Hannah Gurman'),
'alh18@nyu.edu' => t('Alex Halberstadt'),
'rh388@nyu.edu' => t('Rahul Hamid'),
'eh82@nyu.edu' => t('Ethan Harkness'),
'ljh250@nyu.edu' => t('Louise Harpman'),
'sh25@nyu.edu' => t('Scott Hightower'),
'th334@nyu.edu' => t('Thomas Hill'),
'kgh1@nyu.edu' => t('Karen Holmberg'),
'dah17@nyu.edu' => t('Darrel Holnes'),
'mch365@nyu.edu' => t('Molly Horan'),
'kah3@nyu.edu' => t('Karen Hornick'),
'kdh4@nyu.edu' => t('Kristin Horton'),
'jmh29@nyu.edu' => t('Joyce Howard'),
'abh5@nyu.edu' => t('A.B. Huber'),
'amin.husain@gmail.com' => t('Amin Husain'),
'mwj214@nyu.edu' => t('Myles Jackson'),
'dwj3@nyu.edu' => t('Dale Jamieson'),
'mwj3@nyu.edu' => t('Mitchell Joachim'),
'tlj3@nyu.edu' => t('Trevor Jockims'),
'baj4@nyu.edu' => t('Barbara Jones'),
'jj54@nyu.edu' => t('John Jost'),
'sk168@nyu.edu' => t('Selin Kalaycioglu'),
'dk52@nyu.edu' => t('Deborah Kapchan'),
'nk50@nyu.edu' => t('Nina Katchadourian'),
'rtk1@nyu.edu' => t('Rosanne Kennedy'),
'trk5@nyu.edu' => t('Thomas Kennon'),
'bmk7@nyu.edu' => t('Bruce King'),
'dmk6@nyu.edu' => t('David King'),
'eck257@nyu.edu' => t('Eugenia Kisin'),
'ck56@nyu.edu' => t('Carolyn Kissane'),
'jl24@nyu.edu' => t('Jill Lane'),
'atl1@nyu.edu' => t('Andre Lepecki'),
'bl466@nyu.edu' => t('Bradley Lewis'),
'al260@nyu.edu' => t('Philip Libby'),
'sl2@nyu.edu' => t('Susan Linfield'),
'ml122@nyu.edu' => t('Moya Luckett'),
'ral13@nyu.edu' => t('Ritty Lukose'),
'sm173@nyu.edu' => t('Silvia Maier'),
'jmm2@nyu.edu' => t('Julie Malnig'),
'pgm3@nyu.edu' => t('Patrick McCreery'),
'elm1@nyu.edu' => t('Edward Melnick'),
'em113@nyu.edu' => t('Eve Meltzer'),
'km96@nyu.edu' => t('Keith Miller'),
'lm157@nyu.edu' => t('Lynn Minnaert'),
'mm11@nyu.edu' => t('Bella Mirabella'),
'am128@nyu.edu' => t('Ali Mirsepassi'),
'mm6439@nyu.edu' => t('Meleko Mokgosi'),
'eam2035@nyu.edu' => t('Elizabeth Morano'),
'imm270@nyu.edu' => t('Irene Morrison-Moncure'),
'sem2@nyu.edu' => t('Sara Murphy'),
'cn23@nyu.edu' => t('Chitra Neogy'),
'vn10@nyu.edu' => t('Vasuki Nesiah'),
'aln2@nyu.edu' => t('Anthony Nicotera'),
'ao639@nyu.edu' => t('Anastasiya Osipova'),
'cp57@nyu.edu' => t('Crystal Parikh'),
'akp220@nyu.edu' => t('Amanda Petrusich'),
'kpf2@nyu.edu' => t('Kimberly Phillips-Fein'),
'sep1@nyu.edu' => t('Stacy Pies'),
'mp993@nyu.edu' => t('Millery Polyne'),
'tp32@nyu.edu' => t('Todd Porterfield'),
'kop2001@nyu.edu' => t('Kathryn Posin'),
'jrp6@nyu.edu' => t('J Powell'),
'mtp5@nyu.edu' => t('Myisha Priest'),
'jar303@nyu.edu' => t('Jean Railla'),
'pr9@nyu.edu' => t('Peter Rajsingh'),
'bpr212@nyu.edu' => t('Benjamin Ratliff'),
'wsr1@nyu.edu' => t('William Rayner'),
'mr105@nyu.edu' => t('Mark Read'),
'jar31@nyu.edu' => t('Jacob Remes'),
'cer202@nyu.edu' => t('Carlos Restrepo'),
'lr33@nyu.edu' => t('Lee Robbins'),
'ajr6@nyu.edu' => t('Andrew Romig'),
'ser406@nyu.edu' => t('Sarah Rothberg'),
'ir39@nyu.edu' => t('Ignazia Rubino'),
'ar31@nyu.edu' => t('Antonio Rutigliano'),
'jms36@nyu.edu' => t('Jason Samuels'),
'ls71@nyu.edu' => t('Laszlo Santha'),
'ls33@nyu.edu' => t('Leslie Satin'),
'mas28@nyu.edu' => t('Melissa Schilling'),
'es38@nyu.edu' => t('Eugene Secunda'),
'ts307@nyu.edu' => t('Thomai Serdari'),
'des1@nyu.edu' => t('Dennis Shasha'),
'jss518@nyu.edu' => t('Joshua Shirkey'),
'cs97@nyu.edu' => t('Clay Shirky'),
'gms1@nyu.edu' => t('George Shulman'),
'ls104@nyu.edu' => t('Laura Slatkin'),
'jls9@nyu.edu' => t('Judith Sloan'),
'cts233@nyu.edu' => t('Chadwick Smith'),
'ns23@nyu.edu' => t('Nancy Smithner'),
'ss9872@nyu.edu' => t('Stanislav Sobolevsky'),
'als10@nyu.edu' => t('Amy Spellacy'),
'ams45@nyu.edu' => t('Andrew Spence'),
'ms5100@nyu.edu' => t('Matthew Stanley'),
'rs2901@nyu.edu' => t('Robyn Stein'),
'kms5@nyu.edu' => t('Kristi Steinmetz'),
'js9@nyu.edu' => t('Jane Stone'),
'lms9@nyu.edu' => t('Lisa Stulberg'),
'sbt3@nyu.edu' => t('Scott Taitel'),
'it11@nyu.edu' => t('Ido Tavory'),
'mlt8@nyu.edu' => t('Meredith Theeman'),
'st35@nyu.edu' => t('Selma Thompson'),
'yt21@nyu.edu' => t('Yevgeniya Traps'),
'ct36@nyu.edu' => t('Christopher Trogan'),
'vv2@nyu.edu' => t('Vasundara Varadhan'),
'gtv2@nyu.edu' => t('Gregory Vargo'),
'av48@nyu.edu' => t('Alejandro Velasco'),
'dv363@nyu.edu' => t('Daniel Viehoff'),
'mvv221@nyu.edu' => t('Maya Vinokour'),
'ev247@nyu.edu' => t('Eugene Vydrin'),
'lmw242@nyu.edu' => t('Lauren Walsh'),
'saw343@nyu.edu' => t('Sonia Werner'),
'dw37@nyu.edu' => t('Deborah Willis'),
'dw9@nyu.edu' => t('Darrell Wilson'),
'rsw5@nyu.edu' => t('Russell Winer'),
'slw13@nyu.edu' => t('Susanne Wofford'),
'ws848@nyu.edu' => t('Winifred Wu'),
'oiz203@nyu.edu' => t('Alisa Zhulina'),
'arz2@nyu.edu' => t('Angela Zito'),
'write in email' => t('Other')
	);
}

/**
 * Options list containing AP Courses.
 */
function _ap_courses($component, $flat, $arguments) {
  return array(
            'Art History' => t('Art History'),
            'Biology' => t('Biology'),
            'Calculus AB' => t('Calculus AB'),
            'Calculus BC' => t('Calculus BC'),
            'Chemistry' => t('Chemistry'),
            'Chinese Language and Culture' => t('Chinese Language and Culture'),
            'Computer Science A' => t('Computer Science A'),
            'Computer Science AB' => t('Computer Science AB'),
            'Computer Science Principles' => t('Computer Science Principles'),
            'English Literature' => t('English Literature'),
            'Environmental Science' => t('Environmental Science'),
            'European History' => t('European History'),
            'French Language' => t('French Language'),
            'French Literature' => t('French Literature'),
            'German Language' => t('German Language'),
            'Italian Language and Culture' => t('Italian Language and Culture'),
            'Japanese Language and Culture' => t('Japanese Language and Culture'),
            'Latin Literature' => t('Latin Literature'),
            'Latin: Vergil' => t('Latin: Vergil'),
            'Macroeconomics' => t('Macroeconomics'),
            'Microeconomics' => t('Microeconomics'),
            'Physics 1' => t('Physics 1'),
            'Physics 2' => t('Physics 2'),
            'Physics B' => t('Physics B'),
            'Physics C—Mech' => t('Physics C—Mech'),
            'Physics C—E&amp;M' => t('Physics C—E&amp;M'),
            'Politics (U.S. Government and Politics)' => t('Politics (U.S. Government and Politics)'),
            'Politics (Comp. Government and Politics)' => t('Politics (Comp. Government and Politics)'),
            'Psychology' => t('Psychology'),
            'Spanish Language' => t('Spanish Language'),
            'Spanish Literature' => t('Spanish Literature'),
            'Statistics' => t('Statistics'),
            'U.S. History' => t('U.S. History'),
            'World History' => t('World History')
  );
}

/**
 * Options list containing Affinity groups.
 */
function _affinity_groups($component, $flat, $arguments) {
  return array(
'Activism and Human Rights' => t('Activism and Human Rights'),
'Art' => t('Art'),
'Business' => t('Business'),
'Computer Science' => t('Computer Science'),
'Data Science' => t('Data Science'),
'Fashion' => t('Fashion'),
'Film and TV' => t('Film and TV'),
'Finance/Economics' => t('Finance/Economics'),
'Gender Studies' => t('Gender Studies'),
'History' => t('History'),
'Literature' => t('Literature'),
'Media and Journalism' => t('Media and Journalism'),
'Music' => t('Music'),
'Performing Arts' => t('Performing Arts'),
'Psychology' => t('Psychology'),
'Sustainability and Environment' => t('Sustainability and Environment'),
'Writing' => t('Writing')
  );
}


/**
 * Options list 
 */
function _lahc($component, $flat, $arguments) {
  return array(

'Liberal Arts Requirement' => array(
    'Humanities' => t('Humanities'),
    'Social Science' => t('Social Science'),
    'Science' => t('Science')
    ),
// — Second option group
'Historical and Cultural Requirement' => array(
    'Premodern' => t('Premodern'),
    'Early Modern' => t('Early Modern'),
    'Global Cultures' => t('Global Cultures')
    )
  );
}

/**
 * Options list 
 */
function _alum($component, $flat, $arguments) {
 $a = array();
 $start = 1973;
 $end = date("Y") + 10;
    for ($x = $start; $x <= $end; $x++) {
    array_push($a,$x);
    } 

    return $a;
}