<?php

/**
 * @file
 * This is a simple module implementing a webform hook to offer Gallatin-specific lists
 * to be used as options in form components.
 */

/**
 * Implementation of hook_webform_select_options_info().
 */
function webform_gallatin_lists_webform_select_options_info() {
  $items = array();

  $items['united_states_canada'] = array(
    'title' => t('US states/Canadian Provinces'),
    'options callback' => '_united_states_canada',
    'file' => 'includes/webform.options.inc',
  );
  $items['class_advisers'] = array(
    'title' => t('Class Advisers'),
    'options callback' => '_class_advisers',
    'file' => 'includes/webform.options.inc',
  );

  return $items;
}


/**
 * Options list containing United States states and territories.
 */
function _united_states_canada($component, $flat, $arguments) {
  return array(
    'Canadian Provinces' => array(
    'AB' => t('Alberta'),
    'BC' => t('British Columbia'),
    'MB' => t('Manitoba'),
    'NB' => t('New Brunswick'),
    'NF' => t('New Foundland'),
    'NT' => t('Northwest Territories'),
    'NS' => t('Nova Scotia'),
    'NU' => t('Nunavut'),
    'ON' => t('Ontario'),
    'PE' => t('Prince Edward Island'),
    'QC' => t('Quebec'),
    'SK' => t('Saskatchewan'),
    'YT' => t('Yukon Territory')
    ),
// — Second option group
'US States' => array(
    'AL' => t('Alabama'),
    'AK' => t('Alaska'),
    'AS' => t('American Samoa'),
    'AZ' => t('Arizona'),
    'AR' => t('Arkansas'),
    'CA' => t('California'),
    'CO' => t('Colorado'),
    'CT' => t('Connecticut'),
    'DE' => t('Delaware'),
    'DC' => t('District of Columbia'),
    'FL' => t('Florida'),
    'GA' => t('Georgia'),
    'GU' => t('Guam'),
    'HI' => t('Hawaii'),
    'ID' => t('Idaho'),
    'IL' => t('Illinois'),
    'IN' => t('Indiana'),
    'IA' => t('Iowa'),
    'KS' => t('Kansas'),
    'KY' => t('Kentucky'),
    'LA' => t('Louisiana'),
    'ME' => t('Maine'),
    'MH' => t('Marshall Islands'),
    'MD' => t('Maryland'),
    'MA' => t('Massachusetts'),
    'MI' => t('Michigan'),
    'MN' => t('Minnesota'),
    'MS' => t('Mississippi'),
    'MO' => t('Missouri'),
    'MT' => t('Montana'),
    'NE' => t('Nebraska'),
    'NV' => t('Nevada'),
    'NH' => t('New Hampshire'),
    'NJ' => t('New Jersey'),
    'NM' => t('New Mexico'),
    'NY' => t('New York'),
    'NC' => t('North Carolina'),
    'ND' => t('North Dakota'),
    'MP' => t('Northern Marianas Islands'),
    'OH' => t('Ohio'),
    'OK' => t('Oklahoma'),
    'OR' => t('Oregon'),
    'PW' => t('Palau'),
    'PA' => t('Pennsylvania'),
    'PR' => t('Puerto Rico'),
    'RI' => t('Rhode Island'),
    'SC' => t('South Carolina'),
    'SD' => t('South Dakota'),
    'TN' => t('Tennessee'),
    'TX' => t('Texas'),
    'UT' => t('Utah'),
    'VT' => t('Vermont'),
    'VI' => t('Virgin Islands'),
    'VA' => t('Virginia'),
    'WA' => t('Washington'),
    'WV' => t('West Virginia'),
    'WI' => t('Wisconsin'),
    'WY' => t('Wyoming')
    )
  );
}

/**
 * Options list containing Class Advisers and emails.
 */
function _class_advisers($component, $flat, $arguments) {
  return array(
    'yt21@nyu.edu' => t('Yevgeniya Traps (First-year)'),
    'cyd.cipolla@nyu.edu' => t('Cyd Cipolla (Sophomore)'),
    'mag19@nyu.edu' => t('Matthew Gregory (Junior)'),
    'meredith.theeman@nyu.edu' => t('Meredith Theeman (Senior)'),
    'benjamin.brooks@nyu.edu' => t('Benjamin Brooks (Senior)'),
    'jss518@nyu.edu' => t('Joshua Shirkey (Transfer)'),
    'lad421@nyu.edu' => t('Lisa Daily (Transfer)')
  );
}